KotatsuApp/kotatsu-parsers

src/main/kotlin/org/koitharu/kotatsu/parsers/site/MadaraParser.kt
In #6d86054 ar code is used to denote language Arabic.
In #9476990 ja code is used to denote language Japanese.
In #93047b2 th code is used to denote language thai.
=> [Madara] Add manga sources 

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/Madara6Parser.kt
allows you to use the function in madaraparser to fix dates, e.g. "2 hours ago", otherwise the app wouldn't display the chapters.
=> Fix uloaddate and force Enables list

src/main/kotlin/org/koitharu/kotatsu/parsers/site/es/TuMangaOnlineParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/FoolSlideParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/Deathtollscans.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/Mangatellers.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/ReaderEvilflowers.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/en/SilentskyScans.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/es/MenudoFansub.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/fr/HniScantrad.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/it/PowerManga.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/it/Ramareader.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/it/ReadNifteam.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/foolslide/pl/Onepiecenakama.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/MadaraParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/es/TempleScanEsp.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/es/TenkaiScan.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/NinjaScan.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/ar/Ozulscans.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/BirdManga.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/Hentai20.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/ja/MangaMate.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/pl/SkanlacjeFeniksy.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/HentaiVNParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/vmp/VmpParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/vmp/es/VerComicsPorno.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/vmp/es/VerMangasPorno.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/util/Jsoup.kt
Add template FoolSlideParser ands sources
fix TuMangaOnlineParser -> close #230 
Sources : 
reader.deathtollscans.net
reader.mangatellers.gr
reader.evilflowers.com
reader.silentsky-scans.net
www.menudo-fansub.com
hni-scantrad.com
reader.powermanga.org
www.ramareader.it
read-nifteam.info
reader.onepiecenakama.pl
birdmanga -> close #67 ( the site given by the issue links to this url ) 
templescanesp.com
tenkaiscan.net
vercomicsporno.com -> close #102 
vermangasporno.com
=> Add template FoolSlideParser ands sources

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/PrismaScansParser.kt
PrismaScan mudou da URL do site
Antigo: PrismaScan
Com
Novo: https://prismacomics.com/
=> prismascan chance Domain

src/main/kotlin/org/koitharu/kotatsu/parsers/site/all/MangaDexParser.kt
Additionally check for the `pornographic` content rating when labeling a work as sfw or nsfw.
=> Fix MangaDex nsfw check

src/main/kotlin/org/koitharu/kotatsu/parsers/ErrorMessages.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/MangaParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/PagedMangaParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/model/ContentRating.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/model/MangaListFilter.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/all/MangaDexParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/be/AnibelParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/fr/BentomangaParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/ru/DesuMeParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/ru/NudeMoonParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/ru/RemangaParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/ru/multichan/ChanParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/ru/rulib/MangaLibParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/uk/HentaiUkrParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/uk/HoneyMangaParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/uk/MangaInUaParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/util/MangaParserEnv.kt, src/test/kotlin/org/koitharu/kotatsu/parsers/MangaParserTest.kt
I just did it on 1 source, because I'm not sure it's the right method to add it.
Plenty of others are compatible ( mangadex , the mangareader template ect ) I'll add them once I know if it's the right method.
I think we need to add an option like for multiple tags to set to true if the source is compatible with tag exclusion.
I've also added a filter for the type of content ( safe / subjective / adult ) which might be a good idea to couple with the app's option to automatically select "safe" on compatible sources if the don't display nsfw content option is enabled.
=> Feature Add Exclude Tags And Content Rating Filter

src/main/kotlin/org/koitharu/kotatsu/parsers/site/ru/multichan/HenChanParser.kt
Decode the url before getting the tag key from the href attribute
=> Fix tag filtering for Russian characters

src/main/kotlin/org/koitharu/kotatsu/parsers/site/zh/Baozimh.kt
The parser was always only getting the first 24 chapters of the manga under the div with `id=chapter-items`.
This pull request is to fix it by adding the rest of the chapters under the div with `id=chapters_other_list`.
=> Baozimh: Fix for not getting all chapter details

src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangabox/MangaboxParser.kt
Currently mangabox sources like manganato return empty result when searched. I found this is because they expect white space to be set as `_` in the query string.
https://github.com/KotatsuApp/kotatsu-parsers/issues/551
=> fix mangaboxparser white space coding in search query

src/main/kotlin/org/koitharu/kotatsu/parsers/site/all/MangaFireParser.kt
otherwise it may not find tag from the map
needed due to https://github.com/KotatsuApp/kotatsu-parsers/pull/776#discussion_r1614657857
=> MangaFire: title case selected tag

kotatsu-parsers-ksp/src/main/kotlin/org/koitharu/kotatsu/parsers/ksp/ParserProcessor.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/Broken.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/MangaSourceParser.kt
The main idea of this concept is marking parsers as "broken" instead of removing. This flag will be added to MangaSource and such sources might be hidden from list/catalog whereas manga from these sources will be available to user (via history/favorites).
Not sure it is a 100% good idea so opinions regarding this feature are welcoming
=> Broken parser annotation

.gitignore, src/main/kotlin/org/koitharu/kotatsu/parsers/site/it/MangaWorld.kt
Closes #840, Closes #663, Closes #438, Closes #817
=> added source MangaWorld

src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/CuuTruyenParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyenHE.kt
- Update Domain: NetTruyenHE (nettruyenhe.com)
- New source:
+ Name: Cứu Truyện
+ Url: https://cuutruyen.net/ - https://nettrom.com/ - https://hetcuutruyen.net/ - https://cuutruyent9sv7.xyz/
+ Nsfw: i dont know (NSFW = false)
This is my first time i wrote Kotlin script so i dont have too much knowledge about this programming language, i just refer to the "Example of Json API usage" at CONTRIBUTING.md and CuuTruyen.kt from [Tachiyomi unofficial source](https://github.com/beer-psi/tachiyomi-unofficial-extensions/blob/master/src/vi/cuutruyen/src/io/github/beerpsi/tachiyomi/extension/vi/cuutruyen/CuuTruyen.kt) to write it, it took me 5-6 days to write it with the help of A.I. so i know it still has a lot of bugs...
+ Info: This site has an API to extract data: https://cuutruyen.net/api/v2
+ …
=> New source pull request + Update domain

src/main/kotlin/org/koitharu/kotatsu/parsers/site/liliana/LilianaParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/liliana/vi/DocTruyen5s.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/vi/HentaiCube.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/ar/Hijala.kt
Add liliana parser + DocTruyen5s source
=> Add + Update sources

src/main/kotlin/org/koitharu/kotatsu/parsers/site/liliana/LilianaParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/LxManga.kt
- Updated all vi manga sources
- Fix filters for Liliana parser, still have chapter count counter and scrape image data bug
- Add Broken tag for LxManga (need fix: only have 1 manga, always ask for login, cant read)
- Need fix: LxManga, TopTruyen, DocTruyen3Q and DocTruyen5s (need liliana parser)
=> Daily update

src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NhatTruyenVN.kt
Fix incorrectly sorting chap numbers + fix display wrong chapter upload date - https://github.com/KotatsuApp/kotatsu-parsers/issues/1190
=> [NhatTruyenVN] Fixes

src/main/kotlin/org/koitharu/kotatsu/parsers/site/liliana/vi/DocTruyen5s.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/ar/Mangarbic.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/vi/HentaiVnPlus.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/vi/TruyenTranhDamMyy.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/vi/TruyenVn.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/otakusanctuary/en/OtakusanEn.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/otakusanctuary/vi/OtakusanVi.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/BlogTruyenParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/CuuTruyenParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/HentaiVNParser.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/LxManga.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/DocTruyen3Q.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyenHE.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyenLL.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyenSSR.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyenUU.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NhatTruyenVN.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/TopTruyen.kt
=> Update sources domain

src/main/kotlin/org/koitharu/kotatsu/parsers/site/galleryadults/all/NHentaiXxxParser.kt
It seems they updated they search endpoint now it doesn't work with `-` for multi-word tags which is present in `key` but not in `title`.   
`key` part left unchanged cause key can be used in dedicated tag/author endpoint as path value    
Also now search support title name search with and without tags and author search
=> [NHentai.xxx] Fix source

src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/FlameComics.kt
They changed the url to 720 here is the url for proof 
now: https://flamecomics.xyz/_next/image?url=https%3A%2F%2Fcdn.flamecomics.xyz%2Fseries%2F133%2Fthumbnail.png&w=640&q=100
the updatet: https://flamecomics.xyz/_next/image?url=https%3A%2F%2Fcdn.flamecomics.xyz%2Fseries%2F133%2Fthumbnail.png&w=720&q=100
=> Update FlameComics large cover art url

src/main/kotlin/org/koitharu/kotatsu/parsers/site/all/HitomiLaParser.kt
Seems largeCoverUrl + preview images for chapter are broken...
Reference from https://github.com/keiyoushi/extensions-source/pull/8204 by @AwkwardPeak7, tks.
Solved #1602
=> [Hitomi.La] Change cdn domain & fix image url logic

src/main/kotlin/org/koitharu/kotatsu/parsers/site/ru/DesuMeParser.kt
Desu.me recently started new mirror domain "desu.store".  Moreover, original domain "desu.me" are down for several days, so it will be handy to have another option.
=> Update domain list of Desu

src/main/kotlin/org/koitharu/kotatsu/parsers/site/galleryadults/all/HentaiRead.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/NhentaiWorld.kt, src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/MeHentaiVN.kt
Here is what I did:
- Fix lines 
- Re-write **fetchTags()** due to source changed (now tags data is retrieved in seperate Js file, not from main .html). Basically this source works fine in the app but it can't retrieve tags, so that why I only touched fetchTags function.
- Function **getDetails** now fectch manga's title as well (to pass MangaParserTest::link)
- Re-write **getListPage()** due to source changed (they changed how this website handles searching, now this source has filter with multiple tags and tag exclude enabled).
- Minor-modify **getDetails()** and **parseSearchList()** to pass MangaParserTest::link (now it fetch title as well)
- Re-write **getPages()**. Rather than using httpGet to verify if the content-type is "image/", I simply check if the URL in the \<img\> tag is …
=> Some fixes for sources (#1604)

src/main/kotlin/org/koitharu/kotatsu/parsers/site/ru/ZenMangaParser.kt
`width=1600` needs to be concatenated with `&` istead of `?`
```
org.jsoup.HttpStatusException: Forbidden. Status=403, URL=[https://cdn1.manga.men/chapters/d0bd2e80-c180-420a-8eae-d6c30f26f068/5db40151-1ef5-46d5-8d9a-c39428175fcd.jpeg?st=B9M6rsFevIxM_PT0iPE38A&e=1756888258?width=1600]
```
=> FIx ZenManga manga page url
