src/main/kotlin/org/koitharu/kotatsu/parsers/site/MadaraParser.kt

11 New Sources have been added.
Please check and merge this PR.

Add some Madara sites

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/MangaInUaParser.kt

Ukrainian source request #14
TODO:

[New source] MangaInUa

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/MadaraParser.kt

Have removed mangaweebs as many are facing issues due to ISP.

[Madara] Add ReadManwha, X2Manga

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/Madara5Parser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/Madara6Parser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/MadaraParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/TatakaeScansParser.kt

~~Problems with chapter list parsing...~~

[Tatakae Scans] New source

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/BlogTruyenParser.kt

Closes https://github.com/KotatsuApp/kotatsu-parsers/issues/93

[BlogTruyen] Fix image src attr change

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/Manhwa18Parser.kt

Closes https://github.com/KotatsuApp/kotatsu-parsers/issues/90

[Manhwa18] New source

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/MangaReaderParser.kt

Closes https://github.com/KotatsuApp/kotatsu-parsers/issues/118, https://github.com/KotatsuApp/kotatsu-parsers/issues/109, https://github.com/KotatsuApp/kotatsu-parsers/issues/85, https://github.com/KotatsuApp/kotatsu-parsers/issues/82, https://github.com/KotatsuApp/kotatsu-parsers/issues/81, https://github.com/KotatsuApp/kotatsu-parsers/issues/78, https://github.com/KotatsuApp/kotatsu-parsers/issues/60

[MangaReadTheme] Add some new sources using MangaReader theme

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/MadaraParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/MangaReaderParser.kt

Arabic Site To Add: swatmanga.me (showing chapter not found and description not found)

Add: KomikManga & Fixes

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/TruyentranhLHParser.kt

[TruyentranhLH]: New source

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/HoneyMangaParser.kt

Didn't implement a filter by genre.

[New source] HoneyManga

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/MangaReaderParser.kt

I was finally able to test it at home and it works perfectly.
Could you add it, thank you.

Add Phenixscans.fr

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/MangaReaderParser.kt

add epsilonscan.fr ( +18 ) "fr"
add legacy-scans.com "fr"

Add 2 source fr on MangaReaderParser

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/JapScanParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/grouple/GroupleParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/MadaraParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/MangaCultivator.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/Manhuasy.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/ApenasmaisumYaoi.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/Leitorizakaya.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/LimaScans.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/SinensisScans.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/util/CryptoAES.kt

I'm not sure that the code for decrypting the images is "clean" - I'll leave it to you to optimize it if possible - but for moment it works. All the sites below it needed this bit of script to work.
fix japscan -> close #211 
new source : 
sinensisscans.com
limascans.xyz/v2/
leitorizakaya.net 18
mangacultivator.com
www.manhuasy.com
apenasmaisumyaoi.com 18

Add source and create decode url image

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/HentaiVNParser.kt

Add new source HentaiVN

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/Hentai20.kt

quick fix hentai20 move to tempalte mangareader

quick fix hentai20 move to tempalte mangareader

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/ar/Mangarbic.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/vi/Mi2Manga.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/QueenScans.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/id/Duniakomik.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/nepnep/NepnepParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/nepnep/en/Manga4Life.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/nepnep/en/MangaSee.kt

add source and move Manga4Life to tempalte parser
and fix url Duniakomik
sources :
www.mi2manga2.com
mangasee123.com -> close #110
ps you could close these info issues as a comment.
close #70 
close #64 
close #73
close #123 
close #134 
close #74

add source and move Manga4Life to tempalte parser

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/uk/HoneyMangaParser.kt

This fixes the search in this site since they changed the link to a different one

[HoneyManga] Change search url

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/KskMoe.kt

~Users will need to update their chapter list.~
Tested in Kotatsu dev with `DummyParser`.

KskMoe: get original quality images

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/fmreader/FmreaderParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/fmreader/es/OlimpoScans.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/heancms/pt/ReaperScansPt.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/ar/MangaLekNet.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/es/GanzoScan.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/FlowerManga.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/KakuseiProject.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/SweetScan.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/CypherScans.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/id/WarungKomik.kt

olimposcans.com
manga-lek.net
ganzoscan.com
flowermanga.com
kakuseiproject.com.br
sweetscan.net
cypherscans.xyz
warungkomik.com
fix 
mangalionz.com -> mangalionz.org
add url on Reaper Scans Pt -> reaperbr.online

Add sources

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/LineWebtoonsParser.kt

Website url: https://webtoons.com
It uses the API of mobile app (https://play.google.com/store/apps/details?id=com.naver.linewebtoon)
This implementation supports only the "Canvas" webtoons (not "Originals") and only english language.
The language should pretty easy to change (though I don't know how to represent it in the app. maybe make these into different sources?). The "Originals" use a slightly different API with different endpoint addresses and I haven't looked at it too deep.

Add Line Webtoons sources (webtoons.com)

---

src/main/kotlin/org/koitharu/kotatsu/parsers/model/MangaState.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/fr/BentomangaParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/fr/FmTeam.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/heancms/HeanCms.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/heancms/es/YugenMangasEs.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/MadaraParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/MangaReaderParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/nepnep/NepnepParser.kt

To finish the main manga statuses, we can add this one.
And I've already integrated the status from various sources, so the main ones are based on madara and mangareader.
close -> #228

add hiatus

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/Neoxscans.kt

Neoxscan change url: "https://nexoscans.com/"

Neoxscan change url

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/all/NineNineNineHentaiParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/fr/VfScan.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/tr/MangaKings.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/ZeistMangaParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/ar/Hijala.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/ar/LonerTl.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/ar/MangaAiLand.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/ar/MangaSoul.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/ar/RocksManga.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/ar/YokaiTeam.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/id/AsupanKomik.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/id/KlManhua.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/id/KomikRealm.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/id/Mikoroku.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/id/ShiyuraSub.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/id/Sobatmanku.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/id/ToonCubus.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/pt/AnimeXNovel.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/pt/ElevenScanlator.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/pt/GalaxScans.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/pt/GuildaTierDraw.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/pt/MaxgsScan.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/pt/TyrantScans.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/pt/WolfScanBr.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/tr/EpikMan.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/tr/Mikrokosmosfb.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/tr/SnscoeurTurkey.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/util/String.kt

Add ZeistMangaParser
- Sources : 
www.animexnovel.com close : #407
www.asupankomik.my.id
elevenscanlator.blogspot.com close :  #343
galaxscans.blogspot.com
www.guildatierdraw.com close : #409
hijala.blogspot.com close : #72
klmanhua.blogspot.com
www.komikrealm.my.id
loner-tl.blogspot.com
manga-ai-land.blogspot.com
mangakings.com.tr
www.manga-soul.com
www.mikoroku.web.id
mikrokosmosfb.blogspot.com close : #295
www.rocks-manga.com
shiyurasub.blogspot.com
snscoeurturkey.blogspot.com
www.sobatmanku19.site
www.tooncubus.top
www.tyrantscans.com close : #363
yokai-team.blogspot.com
www.maxgsscan.online close : #364
wolfscanbr.blogspot.com close : #361
add .urlDecode()
Url www.vfscan.cc

Add ZeistMangaParser

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/all/HitomiLaParser.kt

I dismissed this in their scripts as the thumbnails worked fine but now they broke

HitomiLa: fix thumbnails

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/id/Shinigami.kt

* Previous url got banned on Indonesia

src: id/shinigami.kt: Change url source

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/galleryadults/all/NHentaiParser.kt

Fix popular page url

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/heancmsalt/es/MangaEsp.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/likemanga/en/ZinManga.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/ResetScans.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/es/EmperorScan.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/es/RagnarokScanlation.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/fr/LunarHentai.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/WickedWitchScan.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/LuaScans.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/LuminousScans.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/MagusManga.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/Nightscans.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/fr/LunarScans.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/tr/RobinManga.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/tr/SummerToon.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zeistmanga/ar/RocksManga.kt

Fix for #578, #507, #571, #573.

Update domains name

---

src/main/kotlin/org/koitharu/kotatsu/parsers/model/Manga.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/all/WebtoonsParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/ar/TeamXNovel.kt

Added support for webtoons originals.
Initialization is a bit slow since the webtoons api for originals(different from canvas (LineWebtoon source)) is DOGSHIT and doesn't support pagination. After it's fine since I'm caching the list.

Feature webtoon original

---

.gitignore
src/main/kotlin/org/koitharu/kotatsu/parsers/site/galleryadults/all/NHentaiParser.kt

New feature : Can now search by number in nhentai, and manga now show full name so that when you download you get the full name as requested in issue #553.
Fix issue : #610, #419, #553

Feature search by number

---

.idea/.gitignore
build.gradle
src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/ReaperComics.kt

Added search support for reaperscans.com , and also fixed the issue with only 32 chapters displayed.
Since reaperscans has a rate limit, manga with a lot of chapters will take a bit longer to load.
Closes #445 
Closes #616

Feature search reaper

---

.idea/.gitignore
src/main/kotlin/org/koitharu/kotatsu/parsers/site/all/WebtoonsParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/nepnep/NepnepParser.kt

Added sort by popular / updated for manga4life.com and mangasee123.com.
Also fixed webtoons (originals) sort by updated.
Closes #536
Closes #621

Feature manga4life sort

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/MangaTownParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/Neoxscans.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/RandomScans.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/Nettruyenmax.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zh/Baozimh.kt

Fixed domain name changes:
Closes #618 
Closes #617 
Closes #593 
Fixed issue for Mangatown and Baozimh:
Closes #592
Closes #591

Fix source domain and issue

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/heancms/en/OmegaScans.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zh/Baozimh.kt

Fix Omegscans

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/MangaReaderParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/FreakComic.kt

I didn't expect the pr to get merged so soon 😅
closes #640
- update selectors on Freakcomic

some more fixes 

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/heancms/pt/ModeScanlator.kt

new source added modescanlator

---

build.gradle
src/main/kotlin/org/koitharu/kotatsu/parsers/MangaLoaderContext.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/bitmap/Bitmap.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/bitmap/Rect.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/all/MangaReaderToParser.kt
src/test/kotlin/org/koitharu/kotatsu/parsers/MangaLoaderContextMock.kt

closes #732
closes #669
closes #234
see  https://github.com/KotatsuApp/Kotatsu/pull/894 for app side changes

MangaReader.To and basic descrambling api

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/RizzComic.kt

Fixed filters and added search support for RizzFables, partially resolving issue #775.

fix filters, added search support for RizzFables

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/ShibaManga.kt

fix title selector

---

.gitignore
src/main/kotlin/org/koitharu/kotatsu/parsers/site/zh/Baozimh.kt

Fix Baozimh select chapter

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/AquaManga.kt

update aquamanga domain

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/it/MangaWorld.kt

Fix Mangaworld

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/it/MangaWorld.kt

Added status filter, added types (Manga, Manhwa, Manhua) in the genres list,
added sort by updated but only for the main page (without filters) since it is not supported by the website, meaning you can't use other tags with the sort by updated.
Closes #849

Feature mangaworld

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/it/mangaworld/MangaWorldParser.kt

fixed mangaworld pages

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/Manhuaplus.kt

domain change manhuaplus

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/HentaiVNParser.kt

i hope it can solve cloudflare captcha loop

domain change hentaivn

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/HentaiVNParser.kt

Fix cloudflare captcha stuck at redirected site!

Update HentaiVN Domain

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/BlogTruyenParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/BlogTruyenVNParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyen.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyenLL.kt

Fix:
- Can't access to BlogTruyen after 7.4.2 Update: Cannot find "section.list-mainpage.listview" (7.4.1 still works)
- Split BlogTruyen into 2 sources (ID Manga diffs)
- Add new NetTruyen domain / parser

Fix some sources

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/CuuTruyenParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/LxManga.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/Truyenqq.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyen.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyenLL.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyenSSR.kt

Fix something, remove something, add and change something, idk :p

Fix decryptor + Add image reconstructor ?

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/BlogTruyenParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/BlogTruyenVNParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/Truyenqq.kt

+3 Broken Vietnamese sources (checked at 10:51 AM - 3/10/24)

Daily update sources

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/liliana/vi/DocTruyen5s.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/BlogTruyenParser.kt

Closed site, i tried my best to maintain it :p

[BlogTruyen] Fix attempt 1

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/MaidScan.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/vi/Quaanhdaocuteo.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/LxManga.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyenLL.kt

Update some sources domain and fix #1203

Update domain + Fixes

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/FlameComics.kt

So flamecomics.xyz changed their sub urls? i dont know the what its called if you wanto here's the page flamecomics.xyz

Updating FlameComics ListUrl

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/YurinekoParser.kt

[YuriNeko] Fix "File not found" errors

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/vi/Fecomicc.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/DocTruyen3Q.kt

[DocTruyen3Q] Fix missing images

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/CMangaParser.kt

[CManga] New source

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/CuuTruyenParser.kt

Fix timer + Add manga status for CuuTruyen

[CuuTruyen] Fixes

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyen.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyenFE.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyenLL.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyenSSR.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyenUU.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NetTruyenVie.kt

- Close https://github.com/KotatsuApp/kotatsu-parsers/issues/1430
- [NetTruyenFE, NetTruyenLL, NetTruyenSSR, NetTruyenUU] Fix "image src not found" errors
- [NetTruyenVie] Add description

[site/wpcomics/vi] Fixes

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/ru/WaMangaParser.kt

Hi, i got error in app:
```
java.lang.NoSuchMethodError: No virtual method optJSONObject(ILorg/json/JSONObject;)Lorg/json/JSONObject; in class Lorg/json/JSONArray; or its super classes (declaration of 'org.json.JSONArray' appears in /apex/com.android.art/javalib/core-libart.jar)
2025-02-09 19:43:47.071 10838-10896 System.err              org.koitharu.kotatsu.debug           W  	at org.koitharu.kotatsu.parsers.site.ru.WaMangaParser.getDetails(WaMangaParser.kt:104)
2025-02-09 19:43:47.071 10838-10896 System.err              org.koitharu.kotatsu.debug           W  	at org.koitharu.kotatsu.parsers.site.ru.WaMangaParser$getDetails$1.invokeSuspend(Unknown Source:15)
2025-02-09 19:43:47.071 10838-10896 System.err              org.koitharu.kotatsu.debug           W  	at …
```

Fix manga source WaManga

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/ru/WaMangaParser.kt

WaManga has closed public links to file folders, but they have fixed the API. I reworked the logic to fully operate through the API and verified that it works in the application, tests also pass.

[WaManga] source. Use api, instead of html parse

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/vi/HentaiCube.kt

Fix "Root not found" / "Content not found or removed" error [CBHentai]

[CBHentai] Fix tags

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/pt/SssScanlator.kt

Fix chapter number [SssScanlator]

[sources/SssScanlator] Small fixes

---

src/main/kotlin/org/koitharu/kotatsu/parsers/MangaParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/PagedMangaParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/SinglePageMangaParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/model/Manga.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/model/MangaListFilter.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/model/MangaListFilterCapabilities.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/model/search/MangaSearchQuery.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/model/search/MangaSearchQueryCapabilities.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/model/search/QueryCriteria.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/model/search/SearchCapability.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/model/search/SearchableField.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/all/MangaDexParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangabox/MangaboxParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangabox/en/Mangairo.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangabox/en/Mangakakalot.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangabox/en/MangakakalotTv.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangabox/en/Manganato.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/util/SearchQueryConverter.kt
src/test/kotlin/org/koitharu/kotatsu/parsers/MangaParserTest.kt
src/test/kotlin/org/koitharu/kotatsu/parsers/model/search/MangaSearchQueryTest.kt
src/test/kotlin/org/koitharu/kotatsu/parsers/util/ListFilterToSearchQueryConverterTest.kt
src/test/kotlin/org/koitharu/kotatsu/parsers/util/SearchQueryToListFilterConverterTest.kt

Basically it is working POC idea of which is to show a bit different more flexible approach to search query structure.    
It is fanny that i implemented `author` search capability as the showcase how to add new field and then it was implemented in `MangaListFilter` 😅   
It is my first try to use Kotlin so code definitely not ideal and probably not follow Kotlin best practices.    
Honestly i do not expect this change do merge 😂 but it is 99,9% working implementation which should not break old library users.   
This proposal introduces `MangaSearchQuery` as a new search abstraction to replace `MangaListFilter`. Alongside this change, a new `searchManga` method is added to `MangaParser`, which is intended to replace the existing `getList` method. These changes aim to improve the …

POC: New MangaSearchQuery implementation proposal

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/galleryadults/all/NHentaiXxxParser.kt

[NHentai.xxx] Fix source

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/NhentaiWorld.kt

Solved https://github.com/KotatsuApp/kotatsu-parsers/issues/1445

[Nhentai World] Fix chapters list

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/NhentaiWorld.kt

[Nhentai World] Fix tags

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/liliana/vi/DocTruyen5s.kt

[DocTruyen5s] Fix "521 errors" with chapter images

[DocTruyen5s] Fixes

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/DocTruyen3Q.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/TopTruyen.kt

[TopTruyen + DocTruyen3Q] Fix chapter images

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/vi/HentaiZ.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/CMangaParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/DuaLeoTruyen.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/Hentai18VN.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/HentaiVnBuzz.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/LxManga.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/NhentaiWorld.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/WpComicsParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/DocTruyen3Q.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/HamTruyen.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/NewTruyen.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/TopTruyen.kt

[site/vi] Update sources domain

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/wpcomics/vi/DocTruyen3Q.kt

Use better logic to handle chapter images and avoid "Content not found or removed" errors
Solved #1604

[DocTruyen3Q] Fix chapter images + Improvements

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/FlameComics.kt

Changing coverUrl widht to the correct number

[FlameComics] Fixing coverurl

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/hotcomics/en/HotComics.kt

Solved https://github.com/KotatsuApp/kotatsu-parsers/issues/1717
Reference: https://github.com/keiyoushi/extensions-source/pull/5405

[HotComics] Fix list chaps

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/en/BatCave.kt

[BatCave] Small fixes

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/heancms/HeanCms.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/heancms/en/ReaperComics.kt

Trying to solve https://github.com/KotatsuApp/kotatsu-parsers/issues/1479

[HeanCms] Small improvements

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/all/HitomiLaParser.kt

Trying to fix https://github.com/KotatsuApp/kotatsu-parsers/issues/1688, apply for largeCoverUrl + preview

[Hitomi.la] Small fixes

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/galleryadults/en/HentaiNexus.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/galleryadults/en/HentaiRead.kt

Details in commit messages.
All changed have been tested (Junit and Android device)
Note for HentaiRead:
The author search feature is now functioning, but an error message indicates "Content not found or removed" because the app keeps loading additional data on the next pages, which is not available.

[HentaiNexus + HentaiRead] Small fixes

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/all/HitomiLaParser.kt

Closes #1783, #1688 
See : PR #1754

Fix hitomi red covers

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/ru/ComXParser.kt

Solved https://github.com/KotatsuApp/kotatsu-parsers/issues/1799

[Com-X] Small fixes: Bypass age verification

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/zh/ManhuaguiParser.kt

Fixes user agent and parse errors. Resolves [comment](https://github.com/KotatsuApp/kotatsu-parsers/pull/1812#issuecomment-2929352934) of PR #1812.
- Mobile version of Manhuagui is harder to parse metadata and it will not be supported.
- It seems that `Accept-Encoding` of requests is set to `gzip` by default and it can't be parsed by `Response.parseHtml()`. I am not sure if there are additional settings to fix it, so I decide to enforce the header to `identity` to make sure the responses are plain texts.
- `decompressLZStringFromBase64()` is buggy. Also I am not sure if there is simpler way to write such code.
- Purely clean network
- Self-build Kotatsu source code on commit KotatsuApp/Kotatsu@0ed2232 (I am not using the currently latest commit for I can't compile this version), with the …

[Manhuagui] Fix UA and parse errors

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/MimiHentai.kt

Solved a task in https://github.com/KotatsuApp/kotatsu-parsers/issues/1604

[MimiHentai] Small fixes

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/MadaraParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/vi/HentaiCube.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/MimiHentai.kt

Try to fix duplicated tags in [CBHentai], attempt 1

[CBHentai] Fix duplicated tags

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/CMangaParser.kt

Solved https://github.com/KotatsuApp/kotatsu-parsers/issues/1604

[CManga] Fix chap number

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/MadaraParser.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/vi/HentaiCube.kt

[CBHentai] Add author search + Fix duplicate tags

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/all/MyReadingManga.kt
src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/TruyenHentai18.kt

[TruyenHentai18] Fix getPages

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/fr/RimuScans.kt

Update rimuscans url

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/id/Komikcast.kt

Fix komikscans

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/es/DoujinHentaiNet.kt

[DoujinHentai] Fix doujinhentai

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madtheme/en/ManhuaScan.kt

Closes #1418, closes #1730,closes #1922

[ManhuaScan] Fix source

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/HuntersScan.kt

[HuntersScan] Update domain and fix chapter list

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/Manhastro.kt

A bit scuffed, might fix it later if they update their website.
Closes #1376, closes #1362

[Manhastro] Fix chapter list

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/Mangagg.kt

[Mangagg] Fix chapter list

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/ar/RocksManga.kt

[RocksManga] Update site structure

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/pt/MediocreToons.kt

MediocreToons: Add source

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/ru/ZenMangaParser.kt

ZenManga: Add source

---

src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/LxManga.kt

Add header to fix 404 not found

Update LxManga Parser
